# Copyright 2015 Nicta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ELK
---
# Elasticsearch
- name: check if elasticsearch is present
  stat: path=/usr/share/elasticsearch/bin/elasticsearch
  register: result
  ignore_errors: True
- name: elasticsearch repo1
  shell: rpm --import http://packages.elasticsearch.org/GPG-KEY-elasticsearch
  when: result.stat.exists == false
- name: elasticsearch repo2
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo mode=0755
  when: result.stat.exists == false
- name: elasticsearch install
  yum: name=elasticsearch-1.4.4 state=present
  when: result.stat.exists == false
- name: elasticsearch config
  shell: "echo 'network.host: localhost' >> /etc/elasticsearch/elasticsearch.yml"
  when: result.stat.exists == false

# KIBANA
- name: check if kibana is present
  stat: path=/opt/kibana/bin/kibana
  register: result
  ignore_errors: True
- name: kibana install
  shell: "cd /opt; \
    wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz; \
    tar xvf kibana-4.0.1-linux-x64.tar.gz; \
    mv kibana-4.0.1-linux-x64 /opt/kibana; \
    rm -fr kibana-4.0.1-linux-x64.tar.gz;"
  when: result.stat.exists == false
- name: kibana config
  template: src=kibana.yml.j2 dest=/opt/kibana/config/kibana.yml mode=0755
  when: result.stat.exists == false
- name: kibana init
  template: src=kibana.init.j2 dest=/etc/init.d/kibana mode=0755
  when: result.stat.exists == false

# NGINX
- name: check if nginx is present
  stat: path=/usr/sbin/nginx
  register: result
  ignore_errors: True
- name: nginx repo
  yum: name=epel-release state=present
  when: result.stat.exists == false
- name: nginx install
  yum: name=nginx,httpd-tools state=present
  when: result.stat.exists == false
- name: nginx config
  template: src=kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf mode=0755
  when: result.stat.exists == false

# LOGSTASH
- name: check if logstash is present
  stat: path=/etc/init.d/logstash
  register: result
  ignore_errors: True
- name: logstash repo
  template: src=logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo mode=0755
  when: result.stat.exists == false
- name: logstash install
  yum: name=logstash state=present
  when: result.stat.exists == false
- name: logstash config
  template: src=central.conf.j2 dest=/etc/logstash/conf.d/central.conf mode=0755
  when: result.stat.exists == false
