# MESOS SLAVE
---
- name: mesos slave config
  copy: src=files/mesos-slave.txt dest=/etc/default/mesos-slave mode=0755
- name: mesos slave using docker
  lineinfile: dest=/etc/mesos-slave/containerizers line="docker,mesos" create=yes
- name: mesos slave timeout
  lineinfile: dest=/etc/mesos-slave/executor_registration_timeout line="5mins" create=yes
- name: make sure mesos-slave is stopped
  service: name=mesos-slave state=stopped enabled=no
