# Copyright 2015 Nicta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# MESOS SLAVE
---
- name: mesos slave config
  template: src=mesos-slave.j2 dest=/etc/default/mesos-slave mode=0755
- name: mesos slave using docker
  lineinfile: dest=/etc/mesos-slave/containerizers line="docker,mesos" create=yes
- name: set accepted port range
  lineinfile: dest=/etc/mesos-slave/resources line="ports:[1024-65535]" create=yes
- name: mesos slave timeout
  lineinfile: dest=/etc/mesos-slave/executor_registration_timeout line="5mins" create=yes
- name: make sure mesos-slave is stopped
  service: name=mesos-slave state=stopped enabled=no
