# ANSIBLE
---
- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release.noarch
    - python-pip
    - python-devel
- name: install setuptools
  pip: name=setuptools extra_args='--upgrade'
- name: install ansible
  pip: name=ansible
- name: install boto and awscli
  pip: name={{ item }} state=present
  with_items:
    - boto
    - awscli
    - marathon
- name: install docker-py
  pip: name=docker-py version=1.1.0 state=present
