# General
region: ap-southeast-2
ansible_ssh_user: ubuntu
security_group_name: "{{ cluster_name }}-sg"
billing_tag: "mytag"

# Baking
base_image: "ami-69631053"
instance_name_controller: "{{ cluster_name }}-controller"
instance_name_node: "{{ cluster_name }}-node"
instance_name_logging: "{{ cluster_name }}-logging"
ami_controller: "ami-{{ cluster_name }}-controller-{{ ami_version }}"
ami_node: "ami-{{ cluster_name }}-node-{{ ami_version }}"
ami_logging: "ami-{{ cluster_name }}-logging-{{ ami_version }}"
