# Copyright 2015 Nicta
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DOCKER
---
- name: check if docker is present
  stat: path=/mnt/docker/docker
  register: result
  ignore_errors: True
- name: install the required packages for docker
  yum: name={{ item }} state=latest
  with_items:
    - e4fsprogs
  when: result.stat.exists == false
- name: docker config
  template: src=docker.j2 dest=/etc/sysconfig/docker mode=0755
  when: result.stat.exists == false
- name: install the docker packages
  yum: pkg=docker state=present
  when: result.stat.exists == false
- name: start docker
  service: name=docker state=started enabled=yes
