# DOCKER
---
- name: check if docker is present
  stat: path=/mnt/vol2/docker
  register: result
  ignore_errors: True
- name: install the required packages for docker
  yum: name={{ item }} state=latest
  with_items: 
    - e4fsprogs
  when: result.stat.exists == false
- name: docker config
  template: src=docker.j2 dest=/etc/sysconfig/docker mode=0755
  when: result.stat.exists == false
- name: install the docker packages
  yum: pkg=docker state=present
  when: result.stat.exists == false
- name: start docker
  service: name=docker state=started enabled=yes
