- name: wait for ssh to come up on controller
  hosts: all
  gather_facts: no
  tasks:
    - local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 20
        timeout: 300
        state: started


- name: configure controller
  hosts: controller
  user: root
  sudo: True
  tasks:
    - name: add entry to hosts file
      lineinfile: dest=/etc/hosts line="127.0.0.1 controller registry"

    - name: check if registry is running
      shell: curl -I http://registry:5000/
      register: result
      ignore_errors: True

    - name: docker private registry
      shell: docker run -d
        -e SETTINGS_FLAVOR=s3
        -e AWS_BUCKET={{ clusterous_s3_bucket }}
        -e STORAGE_PATH={{ registry_s3_path }}
        -e AWS_KEY={{ AWS_KEY }}
        -e AWS_SECRET={{ AWS_SECRET }}
        -p 5000:5000 registry
      async: 600
      poll: 3
      when: result|failed

    # Mount volume
    - name: format ebs
      shell: mkfs -t ext4 /dev/xvdf
    - file: path=/home/data state=directory mode=0755
    - name: mount volume /home/data
      mount: name=/home/data src=/dev/xvdf fstype=ext4 state=mounted

    # NFS share
    - name: nfs share
      lineinfile: dest=/etc/exports line="/home/data            *(rw,sync,no_root_squash,no_all_squash)"
    - name: restart nfs
      shell: systemctl restart nfs-server

    # DNS
    - name: get default DNS resolver ip
      shell: grep 'nameserver' /etc/resolv.conf | awk '{ print $2 }'
      register: default_dns_ip
    - name: Add default DNS resolver to mesos-dns
      shell: sed -i -- 's/\["8.8.8.8"\]/\["{{ default_dns_ip.stdout }}"\,"8.8.8.8"\]/g' /opt/mesos-dns/config.json
    - name: check if mesos-dns is running
      shell: ps aux | grep mesos-dns
      register: result
      ignore_errors: True
    - name: start mesos-dns
      shell: service mesos-dns start
      when: result.stdout.find('config.json') == -1

    # Use its own DNS resolver
    - name: mesos-dns
      lineinfile: dest=/etc/resolv.conf regexp='^nameserver' line="nameserver {{ ansible_eth0.ipv4.address }}" mode=0755

    # Copy remote ansible scripts
    - name: copy remote ansible scripts
    # Create Clusterous directory on controller
      file: path=/root/{{ remote_host_scripts_dir }} state=directory mode=0755
    - copy: src={{ remote_scripts_dir }}/ dest=/root/{{ remote_host_scripts_dir }}
    - copy: src={{ remote_scripts_dir }}/ansible.cfg dest=/root/.ansible.cfg
