---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  tasks:
    # Master
    - name: Provisioning master
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: "{{ keypair }}"
        instance_type: "{{ controller_instance_type }}"
        image: "{{ controller_ami_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: true
        #private_ip: "{{ master_private_ip }}"
        wait: yes    
        group: "{{ security_group_name }}"
        instance_tags:  
          Name: "{{ controller_instance_name }}"
          group: "{{ controller_instance_name }}"
        exact_count: 1 
        count_tag:  
          Name: "{{ controller_instance_name }}"
          group: "{{ controller_instance_name }}"
      register: ec2
    # # Master
    # - name: create and attach volume to master
    #   local_action:  
    #     module: ec2_vol
    #     volume_size: 50
    #     device_name: /dev/sdf
    #     region: "{{ region }}"  
    #     instance: "{{ item.id }}"
    #   with_items: ec2.instances

    - name: Wait for ssh to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

