- hosts: localhost  
  connection: local  
  gather_facts: no    
  tasks:
    # Nodes
    - name: Provisioning nodes
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: "{{ keypair }}"
        instance_type: "{{ cluster_node_instance_type }}"
        image: "{{ node_ami_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        wait: yes    
        group: "{{ security_group_name }}"
        instance_tags:  
          Name: "{{ cluster_node_instance_name }}"
          group: "{{ cluster_node_instance_name }}"
          Billing: "{{ billing_tag }}"
        exact_count: "{{ cluster_nodes }}"
        count_tag:  
          Name: "{{ cluster_node_instance_name }}"
          group: "{{ cluster_node_instance_name }}"
      register: ec2
    - name: Wait for ssh to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
