---
- name: sync folder
  hosts: all
  user: root
  sudo: yes
  tasks:
    - name: create remote directory if it doesn't exist
      file: path={{ dst_path }} state=directory mode=0755

    - name: sync folder
      synchronize: src={{ src_path }} dest={{ dst_path }}
      sudo: no
