- hosts: localhost  
  connection: local  
  gather_facts: no    
  tasks:
    # Nodes
    - name: provisioning nodes
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ node_ami_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: no
        wait: yes    
        group: "{{ security_group_name }}"
        instance_tags:  
          Name: "{{ node_name }}"
          group: "{{ node_name }}"
        exact_count: "{{ num_nodes }}"
        count_tag:  
          Name: "{{ node_name }}"
          group: "{{ node_name }}"
      register: ec2
      # TODO: how to wait for ssh to come up?
