- name: run remote
  hosts: all
  user: root
  tasks:
    - name: copy key file
      copy: src={{ key_file_src }} dest={{ remote_dir }}/{{ key_file_name }} mode=0600

    - name: copy vars file
      copy: src={{ vars_file_src }} dest={{ remote_dir }}/{{ vars_file_name }}

    - name: run remote ansible
      shell: ansible-playbook -i hosts --private-key {{ key_file_name }} --extra-vars @{{ vars_file_name }} {{ playbook_file }}
      args:
        chdir: "{{ remote_dir }}"

    - name: delete key file and vars file
      file: path={{ remote_dir }}/{{ key_file_name }} state=absent
    - file: path={{ remote_dir }}/{{ vars_file_name }} state=absent
